### ISSUE TITLE
Broken dependency smooth star rating

### ISSUE THREAD

**Issue by tverra** [Skyost/RateMyApp#49] opened 2020-05-14 09:57 UTC
The parameter onRatingChanged on SmoothStarRating is removed in one of the new versions. This causes a compilation error on line 272 in dialogs.dart. A workaround is to change the version of smooth_star_rating from `^1.0.4+2` to `1.0.4+2` in the pubspec.

**Comment by Skyost** [comment] 2020-05-14 10:08
Duplicate of #48.

**Closed by Skyost** 2020-05-14 10:08 UTC
Labels: bug
