### ISSUE TITLE
Remind days & remind launches not working

### ISSUE THREAD

**Issue by yenyichau** [Skyost/RateMyApp#74] opened 2020-09-11 06:46 UTC
Hi, 

I was able to pop up the rating dialog at the first day and I pressed later button. When come to the next day it doesn't pop up anymore. Want to know why it doesn't came out after the first day. Below are my setup for RateMyApp.

Init setup :

    RateMyApp rateMyApp = RateMyApp(
    minDays: 0,
    minLaunches: 1,
    remindDays: 1,
    remindLaunches: 1,
    );

Later button onTap : 

    onTap: () async {
        await rateMyApp.callEvent(RateMyAppEventType.laterButtonPressed);
        Navigator.pop<RateMyAppDialogButton>(context, RateMyAppDialogButton.later);
    },

Thanks.

**Comment by Skyost** [comment] 2020-09-11 12:25
Is this a duplicate of #70 ?

**Comment by yenyichau** [comment] 2020-09-11 12:41
> Is this a duplicate of #70 ?

I guess it is because it return true only on the first day. 
 `minDays: 0`
`minLaunches: 1`

After the next day it should return true as well because of  remind but it doesn't return true.
`remindDays: 1`
`remindLaunches: 1`

Any idea how to solve this issue ?

**Comment by Skyost** [comment] 2020-09-11 12:51
If it's a duplicate, I'll close this issue. Let's keep the conversation in #70. Also you may be interested by [the message I've just posted](https://github.com/Skyost/RateMyApp/issues/70#issuecomment-691069098).

**Closed by Skyost** 2020-09-11 12:51 UTC
Labels: bug
