### ISSUE TITLE
Android rating does not appear in google play

### ISSUE THREAD

**Issue by moosalim** [Skyost/RateMyApp#81] opened 2020-10-20 17:52 UTC
**Describe the bug**
When rating in android using non-native dialog, the ratings does not get published/submitted in google play. 
I tired to set for android native dialog `ignoreNativeDialog: Platform.isAndroid,` but the native dialog did not appear on the app although the app is published in google play store.

Note: no issues with IOS, native dialog appear and the rating is published and appears in the app store.

This is my code:

```
RateMyApp rateMyApp = RateMyApp(
    preferencesPrefix: 'rateMyApp_',
    minDays: 7,
    minLaunches: 10,
    remindDays: 7,
    remindLaunches: 10,
    googlePlayIdentifier: '**************',
    appStoreIdentifier: '***********',
  );
```

```
void initState() {
    super.initState();
    fetchData();
    Future.delayed(const Duration(seconds: 1), () {
      _rateMyApp();
    });
  }
```

```
void _rateMyApp() {
    rateMyApp.init().then((_) {
      if (rateMyApp.shouldOpenDialog) {
      rateMyApp.showStarRateDialog(
        context,
        title: 'Rate this App', // The dialog title.
        message:
            'Do you like this app? Please take sometime to rate it', // The dialog message.
        actionsBuilder: (context, stars) {
          return [
            FlatButton(
              child: Text('Ok'),
              onPressed: () async {
                print('Thanks for the ' +
                    (stars == null ? '0' : stars.round().toString()) +
                    ' star(s) !');
                await rateMyApp.callEvent(RateMyAppEventType.rateButtonPressed);
                Navigator.pop<RateMyAppDialogButton>(
                    context, RateMyAppDialogButton.rate);
              },
            ),
          ];
        },
        ignoreNativeDialog:
            Platform.isAndroid, // Set to false if you want to show the Apple's native app rating dialog on iOS or Google's native app rating dialog (depends on the current Platform).
        dialogStyle: DialogStyle(
          // Custom dialog styles.
          titleAlign: TextAlign.center,
          messageAlign: TextAlign.center,
          messagePadding: EdgeInsets.only(bottom: 20),
        ),
        starRatingOptions:
            StarRatingOptions(), // Custom star bar rating options.
        onDismissed: () => rateMyApp.callEvent(RateMyAppEventType
            .laterButtonPressed), // Called when the user dismissed the dialog (either by taping outside or by pressing the "back" button).
      );
          }
    });
  }
```

**Comment by Skyost** [comment] 2020-10-20 19:51
Is this a duplicate of #71 ?

**Comment by moosalim** [comment] 2020-10-21 05:24
I think it is not duplicate, the #71 is questioning the features of this plugin.
where as in my case, I believe it is a bug. 

The native android dialog does not open, and the non-native dialog does not reflect selected rating in google play nor it does  takes them to the corresponding Store as you mentioned in your response to #71.

**Comment by Skyost** [comment] 2020-10-21 14:17
> The native android dialog does not open

See #64 for possible causes.

>  the non-native dialog does not reflect selected rating in google play nor it does takes them to the corresponding Store as you mentioned in your response to #71.

The non-native dialog as nothing to do with Google Play. It's only a mean for you to get the user rating before taking them to the store (using `rateMyApp.launchStore()` for instance) or doing anything else in fact.

**Comment by moosalim** [comment] 2020-10-22 11:16
Thanks for the feedback. now understood.

Question : Is there any way in the code to prompt the non-native dialog if google play decide to inquire showing the native dialog. ?

**Comment by Skyost** [comment] 2020-10-26 21:55
@moosalim Nop because Google doesn't provide any callback for its dialog (similar to Apple).

**Comment by Skyost** [comment] 2020-10-26 21:56
I'm gonna close this issue, but feel free to keep asking me your questions.

**Closed by Skyost** 2020-10-26 21:56 UTC
Labels: bug
