### ISSUE TITLE
Unhandled Exception: PlatformException(activity_is_null, Activity is null., null) ERror

### ISSUE THREAD

**Issue by skykz** [Skyost/RateMyApp#75] opened 2020-09-13 18:46 UTC
- FLutter version 1.20.2
 this error is happened when start application, I did not change anything in code, plz Help?!

**Comment by Skyost** [comment] 2020-09-15 13:56
Duplicate of #66. See [this comment](https://github.com/Skyost/RateMyApp/issues/66#issuecomment-681852094).

**Closed by Skyost** 2020-09-15 13:56 UTC
Labels: bug
